$(document).ready(function(){
    $('.workspace').owlCarousel({
        center:false,
        loop:true,
        margin:10,
        responsiveClass:true,
        merge:true,
        responsive:{
            0:{
                items:1,
                nav:false
            },
            600:{
                items:3,
                nav:false,
                mergeFit:true
            },
            1025:{
                items:4,
                nav:false,
                center:true,
                loop:true,
                autoWidth:false,
                mergeFit:true
            }
        }
    })

    $('.featured').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        merge:true,
        responsive:{
            0:{
                items:1,

            },
            600:{
                items:3,
                nav:false,
                mergeFit:true
            },
            1000:{
                items:4,
                nav:true,
                loop:false,
                mergeFit:false
            }
        }
    })

    $('.brand').owlCarousel({
        loop:true,
        margin:50,
        responsiveClass:true,
        merge:true,
        responsive:{
            0:{
                items:1,
                nav:true
            },
            600:{
                items:3,
                nav:false,
                mergeFit:true
            },
            1000:{
                items:6,
                nav:true,
                loop:true,
                mergeFit:false
            }
        }
    })

    $('.best').owlCarousel({
        loop:true,
        margin:10,
        responsiveClass:true,
        merge:true,
        responsive:{
            0:{
                items:1,
                nav:true
            },
            600:{
                items:3,
                nav:true,
                mergeFit:true
            },
            1000:{
                items:5,
                nav:true,
                loop:true,
                mergeFit:false
            }
        }
    })
});